# Generated by Django 2.2.4 on 2019-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Koordinator',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='baslik',
            field=models.CharField(default='foobar', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='icerik',
            field=models.TextField(default='foobar'),
        ),
        migrations.AddField(
            model_name='post',
            name='resim',
            field=models.ImageField(default='foobar', upload_to=''),
        ),
    ]
