# Generated by Django 2.2.4 on 2019-08-30 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190828_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resim',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.CreateModel(
            name='etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_adi', models.CharField(default='Etkinlik Adı', max_length=50)),
                ('blog_resim', models.ImageField(upload_to='media')),
                ('slide_resim', models.ImageField(upload_to='media')),
                ('icerik', models.TextField(default='İçerik Ekleyiniz')),
                ('saat_tarih', models.DateTimeField(blank=True, null=True)),
                ('yer', models.CharField(default='Etkinlik Adresi', max_length=100)),
                ('Koordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
