# Generated by Django 2.2.4 on 2019-08-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190830_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
