# Generated by Django 2.2.4 on 2019-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='etkinlik_sitesi',
            field=models.CharField(default='www.acmhacettepe.com', max_length=100),
        ),
    ]
