# Generated by Django 2.2.4 on 2019-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_etkinlik_etkinlik_sitesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_başlık', models.CharField(default='Duyuru Adı', max_length=50)),
                ('içerik', models.TextField(default='İçerik ekleyiniz')),
                ('saat_tarih', models.DateTimeField(blank=True, null=True)),
                ('Koordinator', models.CharField(default='Koordinatör', max_length=50)),
                ('resim', models.ImageField(upload_to='media')),
            ],
        ),
    ]
