# Generated by Django 2.2.4 on 2019-08-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_duyurular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyurular',
            old_name='duyuru_başlık',
            new_name='duyuru_baslik',
        ),
    ]
