# Generated by Django 2.2.4 on 2019-08-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190830_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyurular',
            old_name='içerik',
            new_name='icerik',
        ),
        migrations.RenameField(
            model_name='duyurular',
            old_name='Koordinator',
            new_name='koordinator',
        ),
    ]
