# Generated by Django 2.2.4 on 2019-08-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190830_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlik',
            old_name='Koordinator',
            new_name='koordinator',
        ),
    ]
